version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-local
    working_dir: /app
    command: npm run dev
    ports:
      - 3333:3333
    volumes:
      - .:/app
    env_file:
      - .env
    network_mode: "bridge"
